use oracle::Connection;
use std::error::Error;

pub fn save_to_db(db_url: &str, report_data: &str) -> Result<(), Box<dyn Error>> {
    let conn = Connection::connect(db_url, "", "")?;

    let create_table_sql = "
        CREATE TABLE IF NOT EXISTS extracted_report (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            report_data CLOB,
            PRIMARY KEY (id)
        )
    ";
    conn.execute(create_table_sql, &[])?;

    let insert_sql = "INSERT INTO extracted_report (report_data) VALUES (:1)";
    conn.execute(insert_sql, &[&report_data])?;

    conn.commit()?;
    Ok(())
}
